//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismMangementSystemService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CITY()
        {
            this.HOTELS = new HashSet<HOTEL>();
            this.LOCATIONs = new HashSet<LOCATION>();
            this.TOUR_CITY = new HashSet<TOUR_CITY>();
        }
    
        public int CityID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string CityName { get; set; }
        public byte[] UpdationDate { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOTEL> HOTELS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCATION> LOCATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOUR_CITY> TOUR_CITY { get; set; }
    }
}
