//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismMangementSystemService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION_IMAGE
    {
        public Nullable<int> LocationID { get; set; }
        public int Location_Img_ID { get; set; }
        public string Location_IMG_URL { get; set; }
        public string Location_IMG_DESCR { get; set; }
        public byte[] UpdationDate { get; set; }
    
        public virtual LOCATION LOCATION { get; set; }
    }
}
