//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismMangementSystemService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR_CITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOUR_CITY()
        {
            this.TOUR_LOCATION = new HashSet<TOUR_LOCATION>();
        }
    
        public int Tour_City_ID { get; set; }
        public Nullable<int> Tour_Country_ID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> TourID { get; set; }
        public string Tour_City_Name { get; set; }
        public byte[] UpdationDate { get; set; }
    
        public virtual CITY CITY { get; set; }
        public virtual TOUR TOUR { get; set; }
        public virtual TOUR_COUNTRY TOUR_COUNTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOUR_LOCATION> TOUR_LOCATION { get; set; }
    }
}
