//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismMangementSystemService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR_COST
    {
        public int Tout_Cost_ID { get; set; }
        public Nullable<int> Cost_Catagory_ID { get; set; }
        public Nullable<int> TourID { get; set; }
        public Nullable<double> Amount { get; set; }
        public byte[] UpdationDate { get; set; }
    
        public virtual COST_CATAGORY COST_CATAGORY { get; set; }
        public virtual TOUR TOUR { get; set; }
    }
}
