//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismMangementSystemService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR_LOCATION_IMAGE
    {
        public int TOUR_LOC_IMG_ID { get; set; }
        public Nullable<int> Tour_Location_ID { get; set; }
        public string ImageURL { get; set; }
        public string Image_URL_Desc { get; set; }
        public byte[] UpdationDate { get; set; }
    
        public virtual TOUR_LOCATION TOUR_LOCATION { get; set; }
    }
}
