//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismMangementSystemService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR_LOCATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOUR_LOCATION()
        {
            this.TOUR_LOCATION_IMAGE = new HashSet<TOUR_LOCATION_IMAGE>();
        }
    
        public int Tour_Location_ID { get; set; }
        public Nullable<int> Tour_City_ID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> TourID { get; set; }
        public byte[] UpdationDate { get; set; }
    
        public virtual LOCATION LOCATION { get; set; }
        public virtual TOUR TOUR { get; set; }
        public virtual TOUR_CITY TOUR_CITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOUR_LOCATION_IMAGE> TOUR_LOCATION_IMAGE { get; set; }
    }
}
