//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismMangementSystemService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR_COUNTRY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOUR_COUNTRY()
        {
            this.TOUR_CITY = new HashSet<TOUR_CITY>();
        }
    
        public int Tour_Country_ID { get; set; }
        public Nullable<int> TourID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public byte[] UpdationDate { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual TOUR TOUR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOUR_CITY> TOUR_CITY { get; set; }
    }
}
